spring:
  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
#  sql:
#    init:
#      schema-locations: classpath*:db/schema.sql
#      data-locations: classpath*:db/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        # \u81EA\u5B9A\u4E49\u65B9\u8A00\u89E3\u6790\u5668
        dialect_resolvers: top.yxlgx.config.MyStandardDialectResolver
        format_sql: true
        jdbc:
          batch_size: 20
          order_inserts: true
logging:
  level:
    org.hibernate.tool: debug
